services:
    api:
        build: ./api
        command: ["flask","run", "--host=0.0.0.0", "--port=5000"]
        volumes:
            - ./api:/api
        environment:
            - FLASK_ENV=development
            - FLASK_APP=api.py
        ports:
            - '5000:5000'
        networks:
            - frontend
    
    client:
        build: ./client
        command: ["npm", "start"]
        volumes:
            - ./client:/client
            - node-modules:/client/node_modules
        environment:
            - NODE_ENV=development
        ports:
            - '3000:3000'
        depends_on:
            - api
        networks:
            - frontend

volumes:
    node-modules:

networks:
    frontend:
        driver: bridge