services:
    backend:
        build: ./backend
        command: ["flask","run", "--host=0.0.0.0", "--port=5000"]
        volumes:
            - ./backend:/backend
        environment:
            - FLASK_ENV=development
            - FLASK_APP=api.py
        ports:
            - '5000:5000'
        networks:
            - frontend
    
    frontend:
        build: ./frontend
        command: ["npm", "start"]
        volumes:
            - ./frontend:/frontend
            - node-modules:/frontend/node_modules
        environment:
            - NODE_ENV=development
        ports:
            - '3000:3000'
        depends_on:
            - backend
        networks:
            - frontend

volumes:
    node-modules:

networks:
    frontend:
        driver: bridge