name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the frontend image
      run: docker build ./client/ --tag frontend:$(date +%s)
    - name: Build backend image
      run: docker build ./api/ --tag backend:$(date +%s)
